---
- hosts: localhost
  connection: local
  roles:
  - role: aws

- hosts: tag_html_one_page_challenge
  gather_facts: False
  remote_user: ec2-user
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
  roles:
  - role: common
  - role: webserver
