---
key_path: /etc/ssl/private
cert_path: /etc/ssl/certs
key: "{{ key_path }}/apache-selfsigned.key"
cert: "{{ cert }}/apache-selfsigned.crt"
dhparam: "{{ cert }}/dhparam.pem"
config_path: /etc/httpd/conf.d
ssl_config: "{{ config_path }}/ssl.conf"
non_ssl_config: "{{ config_path }}/non-ssl.conf"
httpd_config: /etc/httpd/conf/httpd.conf
docroot: /var/www/ssl