---
# Pick a random subnet
- name: Magic 8 ball of subnets
  set_fact:
    subnet: "{{ item }}"
  with_random_choice:
    - a
    - b
    - c

- name: "set fact public-{{ subnet }}"
  set_fact:
    public_subnet_id: "{{ item.value }}"
  when: (item.key == "public-{{ subnet }}")
  with_items: "{{ vpc_subnet_ids }}"

# Create ssh key pair
- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: "{{ keypair_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: keypair
  tags:
    - ec2_key

- name: Copy EC2 Key Pair private key locally
  copy: 
    content: "{{ keypair.key.private_key }}"
    dest: "{{ ec2_key_directory }}/{{ keypair_name }}"
    mode: 0600
  when: keypair.changed == true

- name: Create EC2 Instances
  ec2:
    image: "{{ ec2_image }}"
    wait: yes
    instance_type: "{{ instance_type }}"
    region: "{{ aws_region }}"
    group: "{{ project_name }}-WebDMZ"
    vpc_subnet_id: "{{ public_subnet_id }}"
    assign_public_ip: yes
    key_name: "{{ keypair.key.name }}"
    count_tag: "{{ ec2_tag }}"
    exact_count: "{{ instance_count }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    