---

# credentials for AWS (encrypted useing a value key)
project_name: ansible_challenge

# general details about our VPC
vpc_name: ansible_challenge_vpc
vpc_dns_zone: ansiblechallenge

# IP CIDR block for the VPC
vpc_cidr_block: 10.0.0.0/16

# External port number to access the app through
ssh_port: 22
http_port: 80
https_port: 443


# a list defining the security groups for our VPC
vpc_security_groups:
  - name: "{{ project_name }}-WebDMZ"
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - "{{ ssh_port }}"
          - "{{ http_port }}"
          - "{{ https_port }}"
      # - proto: tcp
      #   cidr_ip: 0.0.0.0/0
      #   ports:
      #     - 22

# a map defining the subnets we will build in the VPC
# Only using az a, b and c as there are only 3 az's in my test AWS site Sydney
vpc_subnets:
  public-a:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}a"
  public-b:
    cidr: 10.0.4.0/24
    az: "{{ aws_region }}b"
  public-c:
    cidr: 10.0.6.0/24
    az: "{{ aws_region }}c"

# EC2 image details
# ec2_image: ami-006c4604fe559cd9c # AL2
# ec2_image: ami-044b21dabdfb78334 # RHEL 8.3
ec2_image: ami-044c46b1952ad5861 # RHEL8 Free Tier Eligible
instance_type: t2.micro
instance_count: 1
ec2_tag: WebServerAnsibleChallenge
# ec2_key_directory: ~/.ssh/
# keypair_name: ansible_challenge_key
  