  - name: Install apache packages 
    yum:
      name: httpd
      state: present
      use_backend: yum
    become: yes

  # - name: Enable and Start httpd
  #   service:
  #     name: httpd 
  #     enabled: yes
  #     state: started