- name: Creates directory "{{ key_path }}"
  file:
    path: "{{ key_path }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'


- name: Generate openssl private key
  openssl_privatekey:
    path: "{{ key }}"
    size: 2048

- name: Generate csr
  openssl_csr:
    path: "{{ csr }}"
    privatekey_path: "{{ key }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    provider: selfsigned
    path: "{{ cert }}"
    privatekey_path: "{{ key }}"
    csr_path: "{{ csr }}"

#   community.crypto.x509_certificate:
#     path: "{{ cert }}"
#     privatekey_path: "{{ key }}"
#     # csr_path: /etc/ssl/csr/ansible.com.csr
#     provider: selfsigned

# - name: Generate DH Parameters with a different size (2048 bits)
#   openssl_dhparam:
#     path: "{{ dhparam }}"
#     size: 2048

# - name: Find the contents of "{{ cert }}" and assign to variable
#   ansible.builtin.shell: cat "{{ cert }}"
#   register: selfsigned_contents

# - name: Manually append "{{ dhparam }}" to "{{ cert }}"
#   command: cat "{{ dhparam }}" | tee -a "{{ cert }}"
#   when: selfsigned_contents.stdout.find('BEGIN DH PARAMETERS') != -1
